### PR TITLE
Allow _JSON to change the type

### PR DESCRIPTION
**Pull request by janpath**

### CODE REVIEW

**Comment by janpath** [comment]
Is this a bad idea or is this not worth the breaking change or are you just waiting for the next major release to merge this?

**Comment by ChrisPenner** [comment]
I found myself wanting this today; anything holding this up?

**Comment by ekmett** [comment]
See the comment on #29. I don't have an objection to allowing another combinator to have the more general type but the user experience with this when it had the more general type was that it caused you to have to use a ton of manual type annotations everywhere in your code. We deliberately switched to the monomorphic type we have today. It wasn't an oversight.

**Comment by ekmett** [comment]
Addressed in HEAD.

**Comment by ChrisPenner** [comment]
Fantastic! Thanks so much 😄

**Pull request closed without merging**
